certificateAuthorities:
    ca.org1.example.com: # TO REPLACE ca_name 
        tlsCACerts:
            path: /etc/firefly/organizations/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt  #replace org_path
        url: https://ca_org1:7054  #replace ca_url
        grpcOptions:
            ssl-target-name-override: ca.org1.example.com   # TO REPLACE ca_name 
        registrar:
            enrollId: admin
            enrollSecret: adminpw
channels:
    mychannel:   #replace channel name
        orderers:
            - fabric_orderer
        peers:
            fabric_peer:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
client:
    BCCSP:
        security:
            default:
                provider: SW
            enabled: true
            hashAlgorithm: SHA2
            level: 256
            softVerify: true
    credentialStore:
        cryptoStore:
            path: /etc/firefly/organizations/peerOrganizations/org1.example.com/msp  #replace org_path
        path: /etc/firefly/organizations/peerOrganizations/org1.example.com/msp  #replace org_path
    cryptoconfig: 
        path: /etc/firefly/organizations/peerOrganizations/org1.example.com/msp  #replace org_path
    logging:
        level: info
    organization: org1.example.com  #replace org_name
    tlsCerts:
        client:
            cert:
                path: /etc/firefly/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem  #replace org_path
            key:
                path: /etc/firefly/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/FILL_IN_KEY_NAME_HERE  #replace org_path
orderers:
    fabric_orderer:
        tlsCACerts:
            path: /etc/firefly/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/tls-localhost-9054-ca-orderer.pem   #replace orderer path
        url: grpcs://orderer.example.com:7050   #replace orderer url
organizations:
    org1.example.com:  #replace org_name
        certificateAuthorities:   
            - ca.org1.example.com  #replace ca_name
        cryptoPath: /tmp/msp
        mspid: Org1MSP  #replace org MSPID
        peers:
            - fabric_peer
peers:
    fabric_peer:
        tlsCACerts:
            path: /etc/firefly/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/tls-localhost-7054-ca-org1.pem  #replace path
        url: grpcs://peer0.org1.example.com:7051   #replace peer url
version: 1.1.0%F